---
title: "ETC5521 Assignment 1"
subtitle: "Deforestration"
team: Cuscus
author:
  - Pian Li
  - Prachi Jaiswal
date: "`r Sys.Date()`"
output: 
  html_document
---

[This assignment is for ETC5521 Assignment 1 by Team `r rmarkdown::metadata$team` comprising of `r knitr::combine_words(rmarkdown::metadata$author)`.]{style="color:#006DAE;"}


# Introduction and motivation

[FILL] Give the bigger picture of the data, and inspire the reader to learn more about the problem by reading your analysis. 

# Data description

## Data source

We have selected the data from the GitHub webpage (https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-04-06/readme.md) which talks about the drivers of deforestation over years. We have selected six datasets related to deforestation and several variables are analyzed: forest area, deforestation, imported deforestation, exported deforestation, human food, animal food, processed, crop oil and production.

The following is our datasets which were obtained from GitHub’s TidyTuesday:

1. Forest area: 
- entity is a character type that shows the country name.
- code is a character type that shows the country code.
- year is an integer type that shows the year from 1990 to 2020.
- forest_area is a double type that shows the per cent of global forest area.


2. Annual deforestation: 
- entity is a character type that shows the country name.
- code is a character type that shows the country code.
- year is a double type that shows the year from 1990 to 2015.
- deforestation is a double type that shows the deforested area in hectares.


3. Imported deforestation:
- entity is a character type that shows the country name.
- code is a character type that shows the country code.
- year is a double type that shows the year from 2005 to 2013.
- imported deforestation is a double type that shows each country’s imported deforestation, measured in hectares.


4. Exported deforestation:
- entity is a character type that shows the country name.
- code is a character type that shows the country code.
- year is a double type that shows the year from 2005 to 2013.
- exported deforestation is a double type that shows each country’s exported deforestation, measured in hectares.


5. Soybean use:
- entity is a character type that shows the country name.
- code is a character type that shows the country code.
- year is a double type that shows the year from 1961 to 2013.
- human food is a double type that shows soybean use for human food (tempeh, tofu, etc).
- animal feed is a double that shows soybean used for animal food.
- processed is a double that shows soybean processed into vegetable oil, biofuel, processed animal feed.


6. Vegetable oil:
- entity is a character type that shows the country name.
- code is a character type that shows the country code.
- year is an integer type that shows the year from 1961 to 2014.
- crop_oil is a character type that shows crops that were used to produce vegetable oil.
- production is a double type that shows oil production in tonnes. 


## Dataset source
The data is originally obtained from “Our World in Data”. And this article "Forests and Deforestation" is retrieved from: 'https://ourworldindata.org/forests-and-deforestation' and written by Hannah Ritchie and Max Roser (2021).

# Analysis and findings

[FILL] Should include at least one plot or numerical summary for each of your questions, that helps the reader arrive at an answer. You should also write paragraphs describing the methods, summaries and findings. 

# References
